# Revenue per Mille, agreed contractually with Admarketplace.
RPM:
  AU: 0.09
  BR: 0.06
  CA: 0.30
  DE: 0.48
  ES: 0.18
  FR: 0.21
  GB: 0.35
  IN: 0.04
  IT: 0.33
  JP: 0.02
  MX: 0.19
  US: 0.57

# list of direct allocation time windows
# each element in the list is a timeframe
# for the countries specified in markets 
# for which the fraction in allocation is sent
# to Ad Marketplace.  start_month and end_month
# specify the start and end of the time window inclusively
# Both are optional, and the earliest and latest values
# in the data are used to replace them respectively if left out
direct_allocations:
  - markets:
      - DE
      - GB
      - US
    allocation: .95
    start_month: 2023-10
    end_month: 2023-12
  - markets:
      - DE
      - GB
      - US
    allocation: .95
    start_month: 2024-01
    end_month: 2025-01
  - markets:
      - DE
      - GB
      - US
    allocation: .9
    start_month: 2025-02

# specify the output database and table
# to write the data to
output:
  output_database: jsnyder
  output_table: amp_rpm_forecasts