RPM:
  AU: 0.09
  BR: 0.06
  CA: 0.30
  DE: 0.48
  ES: 0.18
  FR: 0.21
  GB: 0.35
  IN: 0.04
  IT: 0.33
  JP: 0.02
  MX: 0.19
  US: 0.57

direct_allocations:
  - markets:
      - DE
      - GB
      - US
    allocation: .95
    start_month: 2023-10
    end_month: 2023-12
  - markets:
      - DE
      - GB
      - US
    allocation: .95
    start_month: 2024-01
    end_month: 2025-01
  - markets:
      - DE
      - GB
      - US
    allocation: .9
    start_month: 2025-02