
####################
# CircleCI configuration reference:
#   https://circleci.com/docs/2.0/configuration-reference
####################
# CircleCI built-in environment variables:
#   https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
####################

set_up_uv: &set_up_uv 
  steps:
      - run: echo "hello world" # run the `echo` command
      - run:
          name: install uv
          command: curl -LsSf https://astral.sh/uv/0.4.8/install.sh | sh
      - run: 
          name: set up env
          command: |
            source $HOME/.cargo/env
            uv sync --frozen



version: 2.1

jobs:
  hello-job:
    <<: *set_up_uv
    docker:
      - image: cimg/python:3.10 # the primary container, where your job's commands are run
    steps:
      - run: uv --version # check out the code in the project directory

workflows:
  my-workflow:
    jobs:
      - hello-job